name: Checks CI/CD

on:
  pull_request:
    branches:
      - putbranchhere

env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

  predeploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: step 1
        run: npm install -g npm

      - name: step 2
        run: npm install

      - name: step 3
        run: npm install sharp

      - name: step 4
        run: npm run build
