name: Deploy Production CI/CD

on:
  push:
    branches:
      - putbranchhere

env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: step 1
        run: npm install -g npm

      - name: step 2
        run: npm install

      - name: step 3
        run: npm install sharp

      - name: step 4
        run: npm run build

  deploy:
    needs: predeploy
    runs-on: ubuntu-latest
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect pull deploy and exit
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORK_DIR }} && git checkout ${{ secrets.SSH_BRANCH }} && git pull origin ${{ secrets.SSH_BRANCH }} && cd .. && bash deploy.sh && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
