version: "3"

volumes:
  production_traefik: {}
  production_nodejs_app: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: image_production_traefik
    depends_on:
      - nodejs-app
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  nodejs-app:
    build:
      context: ./app
      dockerfile: ./compose/production/Dockerfile
    volumes:
      - production_nodejs_app:/nodejs-docker-app
    image: image_production_nodejs_app
